import mongoose from 'mongoose';
import { LEDGER_GROUPS } from '../config/accountGroups.js';

const journalEntryLineSchema = new mongoose.Schema({
  accountId: { type: mongoose.Schema.Types.ObjectId, ref: 'AccountMaster' },
  accountName: { type: String, required: true, trim: true },
  // Shares the canonical list with AccountMaster. This used to be a separate copy
  // that drifted — it was missing 'Indirect Income', so posting service income to
  // the ledger failed validation even after the account itself was created.
  accountGroup: {
    type: String,
    enum: LEDGER_GROUPS
  },
  debit: { type: Number, default: 0, min: 0 },
  credit: { type: Number, default: 0, min: 0 },
  narration: { type: String, trim: true }
});

const journalVoucherSchema = new mongoose.Schema({
  voucherNumber: { type: String, unique: true },
  voucherDate: { type: Date, required: true },
  financialYear: { type: String },
  voucherType: {
    type: String,
    enum: ['Journal', 'Contra', 'Opening Entry', 'Depreciation', 'GST Adjustment', 'Sales', 'Purchase', 'Receipt', 'Payment'],
    default: 'Journal'
  },
  referenceType: {
    type: String,
    enum: ['DealerInvoice', 'SupplierInvoice', 'DealerPayment', 'SupplierPayment', 'SalesOrder', 'PurchaseOrder', 'Manual'],
    default: 'Manual'
  },
  referenceId: { type: mongoose.Schema.Types.ObjectId },
  referenceNumber: { type: String },
  entries: {
    type: [journalEntryLineSchema],
    validate: {
      validator: function (entries) {
        if (entries.length < 2) return false;
        const totalDebit = entries.reduce((s, e) => s + (e.debit || 0), 0);
        const totalCredit = entries.reduce((s, e) => s + (e.credit || 0), 0);
        return Math.abs(totalDebit - totalCredit) < 0.01;
      },
      message: 'Journal entry must have at least 2 lines and total debits must equal total credits'
    }
  },
  totalDebit: { type: Number, default: 0, min: 0 },
  totalCredit: { type: Number, default: 0, min: 0 },
  totalAmount: { type: Number, min: 0 },
  narration: { type: String, trim: true },
  isAutoGenerated: { type: Boolean, default: false },
  status: { type: String, enum: ['Posted', 'Cancelled'], default: 'Posted' },
  cancelledAt: Date,
  cancelledBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  cancelReason: String,
  postingKey: { type: String, trim: true },
  reversalOf: { type: mongoose.Schema.Types.ObjectId, ref: 'JournalVoucher' },
  reversedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'JournalVoucher' },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }
}, { timestamps: true });

// Auto-generate voucher number
journalVoucherSchema.pre('save', async function (next) {
  if (!this.voucherNumber) {
    const year = new Date().getFullYear();
    // Use this.constructor so the count comes from the CURRENT company database
    // (not the default mongoose connection — otherwise numbers collide/duplicate).
    const count = await this.constructor.countDocuments();
    this.voucherNumber = `JV-${year}-${String(count + 1).padStart(4, '0')}`;
  }
  next();
});

journalVoucherSchema.index(
  { postingKey: 1 },
  { unique: true, partialFilterExpression: { postingKey: { $type: 'string' } } }
);

// Export schema for multi-database support
export { journalVoucherSchema };

export default mongoose.model('JournalVoucher', journalVoucherSchema);
