import { journalVoucherSchema } from '../models/JournalVoucher.js';
import { userSchema } from '../models/User.js';

const getModels = (dbConnection) => ({
  JournalVoucher:
    dbConnection.models.JournalVoucher ||
    dbConnection.model('JournalVoucher', journalVoucherSchema),
  User:
    dbConnection.models.User ||
    dbConnection.model('User', userSchema),
});

const round2 = (n) => Math.round((Number(n) + Number.EPSILON) * 100) / 100;

const MAX_LIMIT = 2000;

/**
 * Build the date window for the query.
 * Defaults to today when no range is supplied, matching Tally's Day Book, which
 * opens on the current day.
 */
const buildDateWindow = (fromDate, toDate) => {
  const start = fromDate ? new Date(fromDate) : new Date();
  start.setHours(0, 0, 0, 0);

  const end = toDate ? new Date(toDate) : (fromDate ? new Date(fromDate) : new Date());
  end.setHours(23, 59, 59, 999);

  return { start, end };
};

// @desc    Day Book — every voucher for a period, newest first
// @route   GET /api/day-book
// @access  Private
export const getDayBook = async (req, res) => {
  try {
    const { JournalVoucher } = getModels(req.dbConnection);
    const {
      fromDate,
      toDate,
      voucherType,
      search,
      status,
      page = 1,
      limit = 100,
    } = req.query;

    const { start, end } = buildDateWindow(fromDate, toDate);

    const filter = { voucherDate: { $gte: start, $lte: end } };
    if (voucherType && voucherType !== 'all') filter.voucherType = voucherType;
    if (status && status !== 'all') filter.status = status;

    if (search && search.trim()) {
      const rx = { $regex: search.trim(), $options: 'i' };
      filter.$or = [
        { voucherNumber: rx },
        { narration: rx },
        { referenceNumber: rx },
        { 'entries.accountName': rx },
      ];
    }

    const pageNum = Math.max(1, parseInt(page) || 1);
    const limitNum = Math.min(Math.max(1, parseInt(limit) || 100), MAX_LIMIT);
    const skip = (pageNum - 1) * limitNum;

    const [vouchers, total] = await Promise.all([
      JournalVoucher.find(filter)
        .populate('createdBy', 'name username email')
        .sort({ voucherDate: -1, createdAt: -1 })
        .skip(skip)
        .limit(limitNum)
        .lean(),
      JournalVoucher.countDocuments(filter),
    ]);

    const rows = vouchers.map((v) => {
      const entries = v.entries || [];
      const totalDebit = round2(entries.reduce((s, e) => s + (Number(e.debit) || 0), 0));
      const totalCredit = round2(entries.reduce((s, e) => s + (Number(e.credit) || 0), 0));
      const accountNames = [...new Set(entries.map((e) => e.accountName).filter(Boolean))];

      return {
        _id: v._id,
        voucherNumber: v.voucherNumber || '—',
        voucherDate: v.voucherDate,
        voucherType: v.voucherType || 'Journal',
        referenceType: v.referenceType || null,
        referenceNumber: v.referenceNumber || null,
        narration: v.narration || '',
        status: v.status || 'Posted',
        isAutoGenerated: v.isAutoGenerated === true,
        // First non-tax account is the most useful "with whom" label in the list
        primaryAccount: accountNames.find((n) => !/gst/i.test(n)) || accountNames[0] || '—',
        accounts: accountNames,
        entryCount: entries.length,
        totalDebit,
        totalCredit,
        createdBy: v.createdBy?.name || v.createdBy?.username || null,
      };
    });

    // Summary across the whole filtered set (not just this page)
    const typeAgg = await JournalVoucher.aggregate([
      { $match: filter },
      {
        $group: {
          _id: '$voucherType',
          count: { $sum: 1 },
        },
      },
      { $sort: { count: -1 } },
    ]);

    const totalsAgg = await JournalVoucher.aggregate([
      { $match: filter },
      { $unwind: '$entries' },
      {
        $group: {
          _id: null,
          totalDebit: { $sum: '$entries.debit' },
          totalCredit: { $sum: '$entries.credit' },
        },
      },
    ]);

    res.json({
      success: true,
      data: {
        fromDate: start,
        toDate: end,
        rows,
        summary: {
          totalVouchers: total,
          totalDebit: round2(totalsAgg[0]?.totalDebit || 0),
          totalCredit: round2(totalsAgg[0]?.totalCredit || 0),
          byType: typeAgg.map((t) => ({ voucherType: t._id || 'Journal', count: t.count })),
        },
        pagination: {
          currentPage: pageNum,
          totalPages: Math.ceil(total / limitNum),
          totalItems: total,
          itemsPerPage: limitNum,
        },
        note: 'Every posted voucher for the selected period, newest first. Built from journal vouchers.',
      },
    });
  } catch (error) {
    console.error('Day Book error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Day Book — full entry breakdown of one voucher
// @route   GET /api/day-book/:id
// @access  Private
export const getDayBookVoucher = async (req, res) => {
  try {
    const { JournalVoucher } = getModels(req.dbConnection);
    const voucher = await JournalVoucher.findById(req.params.id)
      .populate('createdBy', 'name username email')
      .lean();

    if (!voucher) {
      return res.status(404).json({ success: false, message: 'Voucher not found' });
    }

    const entries = (voucher.entries || []).map((e) => ({
      accountId: e.accountId,
      accountName: e.accountName || '—',
      accountGroup: e.accountGroup || '',
      debit: round2(e.debit || 0),
      credit: round2(e.credit || 0),
      narration: e.narration || '',
    }));

    res.json({
      success: true,
      data: {
        _id: voucher._id,
        voucherNumber: voucher.voucherNumber,
        voucherDate: voucher.voucherDate,
        voucherType: voucher.voucherType,
        referenceType: voucher.referenceType,
        referenceId: voucher.referenceId,
        referenceNumber: voucher.referenceNumber,
        narration: voucher.narration,
        status: voucher.status,
        isAutoGenerated: voucher.isAutoGenerated === true,
        createdBy: voucher.createdBy?.name || voucher.createdBy?.username || null,
        entries,
        totals: {
          totalDebit: round2(entries.reduce((s, e) => s + e.debit, 0)),
          totalCredit: round2(entries.reduce((s, e) => s + e.credit, 0)),
        },
      },
    });
  } catch (error) {
    console.error('Day Book voucher error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Voucher types available in the books, for the Day Book filter
// @route   GET /api/day-book/voucher-types
// @access  Private
export const getVoucherTypes = async (req, res) => {
  try {
    const { JournalVoucher } = getModels(req.dbConnection);
    const types = await JournalVoucher.distinct('voucherType');
    res.json({ success: true, data: types.filter(Boolean).sort() });
  } catch (error) {
    console.error('Voucher types error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

export default { getDayBook, getDayBookVoucher, getVoucherTypes };
