import { tdsEntrySchema } from '../models/TDSEntry.js';
import { journalVoucherSchema } from '../models/JournalVoucher.js';
import { accountMasterSchema } from '../models/AccountMaster.js';
import { assertPeriodOpen, handlePeriodLockError } from '../services/periodLockService.js';

const getModels = (dbConnection) => ({
  TDSEntry: dbConnection.models.TDSEntry || dbConnection.model('TDSEntry', tdsEntrySchema),
  JournalVoucher: dbConnection.models.JournalVoucher || dbConnection.model('JournalVoucher', journalVoucherSchema),
  AccountMaster: dbConnection.models.AccountMaster || dbConnection.model('AccountMaster', accountMasterSchema),
});

const round2 = (n) => Math.round((n + Number.EPSILON) * 100) / 100;

const getOrCreateAccount = async (AccountMaster, accountName, accountGroup, accountType, obType) => {
  let acc = await AccountMaster.findOne({ accountName });
  if (!acc) {
    acc = await AccountMaster.create({
      accountName, accountGroup, accountType,
      openingBalance: 0, openingBalanceType: obType, isSystem: true,
      description: 'Auto-created for TDS postings',
    });
  }
  return acc;
};

const nextVoucherNumber = async (JournalVoucher, date) => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const prefix = `JV-${year}${month}`;
  const last = await JournalVoucher.findOne({ voucherNumber: { $regex: `^${prefix}` } }).sort({ voucherNumber: -1 });
  let seq = 1;
  if (last?.voucherNumber) {
    const n = parseInt(last.voucherNumber.split('-').pop());
    if (!isNaN(n)) seq = n + 1;
  }
  return `${prefix}-${String(seq).padStart(4, '0')}`;
};

// @desc    Create a TDS deduction entry (+ journal voucher)
// @route   POST /api/tds
export const createTDSEntry = async (req, res) => {
  try {
    const { TDSEntry, JournalVoucher, AccountMaster } = getModels(req.dbConnection);
    const {
      supplier, deducteeName, panNumber, section, natureOfPayment,
      baseAmount, tdsRate, deductionDate, referenceNumber, notes,
    } = req.body;

    if (!deducteeName || !section || baseAmount == null || tdsRate == null) {
      return res.status(400).json({ success: false, message: 'Deductee, section, base amount and TDS rate are required' });
    }

    const base = parseFloat(baseAmount) || 0;
    const rate = parseFloat(tdsRate) || 0;
    const tdsAmount = round2((base * rate) / 100);
    const dDate = deductionDate ? new Date(deductionDate) : new Date();

    if (tdsAmount <= 0) {
      return res.status(400).json({ success: false, message: 'TDS amount must be greater than zero' });
    }

    // Block posting into a closed financial year
    await assertPeriodOpen(req.dbConnection, dDate, 'TDS deduction');

    // Accounts: Dr Sundry Creditors (reduce payable) / Cr TDS Payable (govt liability)
    const creditors = await getOrCreateAccount(AccountMaster, 'Sundry Creditors', 'Current Liabilities', 'Liability', 'Cr');
    const tdsPayable = await getOrCreateAccount(AccountMaster, 'TDS Payable', 'Duties & Taxes', 'Liability', 'Cr');

    const voucherNumber = await nextVoucherNumber(JournalVoucher, dDate);
    await JournalVoucher.create({
      voucherNumber,
      voucherDate: dDate,
      voucherType: 'Journal',
      referenceType: 'Manual',
      referenceNumber: referenceNumber || `TDS-${section}`,
      entries: [
        { accountId: creditors._id, accountName: creditors.accountName, accountGroup: creditors.accountGroup, debit: tdsAmount, credit: 0, narration: `TDS ${section} deducted from ${deducteeName}` },
        { accountId: tdsPayable._id, accountName: tdsPayable.accountName, accountGroup: tdsPayable.accountGroup, debit: 0, credit: tdsAmount, narration: `TDS ${section} payable` },
      ],
      totalDebit: tdsAmount,
      totalCredit: tdsAmount,
      totalAmount: tdsAmount,
      narration: `TDS ${section} on payment to ${deducteeName}`,
      isAutoGenerated: true,
      createdBy: req.user?._id,
    });

    const entry = await TDSEntry.create({
      supplier: supplier || undefined,
      deducteeName, panNumber: panNumber || '', section, natureOfPayment: natureOfPayment || '',
      baseAmount: base, tdsRate: rate, tdsAmount,
      deductionDate: dDate, referenceNumber: referenceNumber || '',
      status: 'Deducted', deductionVoucher: voucherNumber,
      notes: notes || '', createdBy: req.user?._id,
    });

    res.status(201).json({ success: true, message: `TDS of ₹${tdsAmount} recorded (voucher ${voucherNumber})`, data: entry });
  } catch (error) {
    if (handlePeriodLockError(error, res)) return;
    console.error('Create TDS entry error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    List TDS entries (filterable)
// @route   GET /api/tds
export const getTDSEntries = async (req, res) => {
  try {
    const { TDSEntry } = getModels(req.dbConnection);
    const { status, section, fromDate, toDate, search, page = 1, limit = 50 } = req.query;
    const q = {};
    if (status) q.status = status;
    if (section) q.section = section;
    if (fromDate || toDate) {
      q.deductionDate = {};
      if (fromDate) q.deductionDate.$gte = new Date(fromDate);
      if (toDate) { const t = new Date(toDate); t.setHours(23, 59, 59, 999); q.deductionDate.$lte = t; }
    }
    if (search) {
      q.$or = [
        { deducteeName: { $regex: search, $options: 'i' } },
        { panNumber: { $regex: search, $options: 'i' } },
        { challanNumber: { $regex: search, $options: 'i' } },
      ];
    }
    const skip = (parseInt(page) - 1) * parseInt(limit);
    const [entries, total] = await Promise.all([
      TDSEntry.find(q).sort({ deductionDate: -1 }).skip(skip).limit(parseInt(limit)).lean(),
      TDSEntry.countDocuments(q),
    ]);
    res.json({ success: true, data: entries, pagination: { currentPage: parseInt(page), totalPages: Math.ceil(total / parseInt(limit)), totalRecords: total } });
  } catch (error) {
    console.error('Get TDS entries error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Mark a TDS entry as deposited (+ journal voucher)
// @route   PATCH /api/tds/:id/deposit  { challanNumber, depositDate }
export const depositTDS = async (req, res) => {
  try {
    const { TDSEntry, JournalVoucher, AccountMaster } = getModels(req.dbConnection);
    const { challanNumber, depositDate } = req.body;

    const entry = await TDSEntry.findById(req.params.id);
    if (!entry) return res.status(404).json({ success: false, message: 'TDS entry not found' });
    if (entry.status === 'Deposited') return res.status(400).json({ success: false, message: 'Already deposited' });

    const depDate = depositDate ? new Date(depositDate) : new Date();
    await assertPeriodOpen(req.dbConnection, depDate, 'TDS deposit');

    // Dr TDS Payable / Cr Bank Account
    const tdsPayable = await getOrCreateAccount(AccountMaster, 'TDS Payable', 'Duties & Taxes', 'Liability', 'Cr');
    const bank = await getOrCreateAccount(AccountMaster, 'Bank Account', 'Current Assets', 'Asset', 'Dr');

    const voucherNumber = await nextVoucherNumber(JournalVoucher, depDate);
    await JournalVoucher.create({
      voucherNumber,
      voucherDate: depDate,
      voucherType: 'Payment',
      referenceType: 'Manual',
      referenceNumber: challanNumber || `TDS-DEP-${entry.section}`,
      entries: [
        { accountId: tdsPayable._id, accountName: tdsPayable.accountName, accountGroup: tdsPayable.accountGroup, debit: entry.tdsAmount, credit: 0, narration: `TDS ${entry.section} deposited` },
        { accountId: bank._id, accountName: bank.accountName, accountGroup: bank.accountGroup, debit: 0, credit: entry.tdsAmount, narration: `TDS ${entry.section} paid to govt` },
      ],
      totalDebit: entry.tdsAmount,
      totalCredit: entry.tdsAmount,
      totalAmount: entry.tdsAmount,
      narration: `TDS ${entry.section} deposit (challan ${challanNumber || ''})`,
      isAutoGenerated: true,
      createdBy: req.user?._id,
    });

    entry.status = 'Deposited';
    entry.challanNumber = challanNumber || '';
    entry.depositDate = depDate;
    entry.depositVoucher = voucherNumber;
    await entry.save();

    res.json({ success: true, message: `TDS deposited (voucher ${voucherNumber})`, data: entry });
  } catch (error) {
    if (handlePeriodLockError(error, res)) return;
    console.error('Deposit TDS error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    TDS summary — section-wise deducted/deposited/payable
// @route   GET /api/tds/summary
export const getTDSSummary = async (req, res) => {
  try {
    const { TDSEntry } = getModels(req.dbConnection);
    const { fromDate, toDate } = req.query;
    const match = {};
    if (fromDate || toDate) {
      match.deductionDate = {};
      if (fromDate) match.deductionDate.$gte = new Date(fromDate);
      if (toDate) { const t = new Date(toDate); t.setHours(23, 59, 59, 999); match.deductionDate.$lte = t; }
    }

    const agg = await TDSEntry.aggregate([
      { $match: match },
      {
        $group: {
          _id: '$section',
          totalBase: { $sum: '$baseAmount' },
          totalTds: { $sum: '$tdsAmount' },
          deposited: { $sum: { $cond: [{ $eq: ['$status', 'Deposited'] }, '$tdsAmount', 0] } },
          count: { $sum: 1 },
        },
      },
      { $sort: { _id: 1 } },
    ]);

    const sections = agg.map((s) => ({
      section: s._id,
      totalBase: round2(s.totalBase),
      totalTds: round2(s.totalTds),
      deposited: round2(s.deposited),
      payable: round2(s.totalTds - s.deposited),
      count: s.count,
    }));

    const totals = sections.reduce(
      (a, s) => ({
        totalBase: round2(a.totalBase + s.totalBase),
        totalTds: round2(a.totalTds + s.totalTds),
        deposited: round2(a.deposited + s.deposited),
        payable: round2(a.payable + s.payable),
      }),
      { totalBase: 0, totalTds: 0, deposited: 0, payable: 0 }
    );

    res.json({ success: true, data: { sections, totals } });
  } catch (error) {
    console.error('TDS summary error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
};
