// services/accountingService.js
// Automatic Accounting Entry Service
// Creates journal entries automatically for business transactions

import { journalVoucherSchema } from '../models/JournalVoucher.js';
import { accountMasterSchema } from '../models/AccountMaster.js';

const getModels = (dbConnection) => {
  return {
    JournalVoucher: dbConnection.models.JournalVoucher || dbConnection.model('JournalVoucher', journalVoucherSchema),
    AccountMaster: dbConnection.models.AccountMaster || dbConnection.model('AccountMaster', accountMasterSchema)
  };
};

/**
 * Get or create system account by name
 */
const getSystemAccount = async (accountName, dbConnection) => {
  const { AccountMaster } = getModels(dbConnection);
  // Try to find by name and system flag first
  let account = await AccountMaster.findOne({ accountName, isSystem: true });
  
  // If not found with system flag, try without it (for older accounts)
  if (!account) {
    account = await AccountMaster.findOne({ accountName });
  }
  
  if (!account) {
    console.warn(`⚠️ System account "${accountName}" not found. Please ensure default accounts are seeded.`);
  }
  
  return account;
};

/**
 * Generate journal voucher number
 */
const generateJournalNumber = async (dbConnection) => {
  const { JournalVoucher } = getModels(dbConnection);
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  
  const prefix = `JV-${year}${month}`;
  const lastJournal = await JournalVoucher.findOne({
    voucherNumber: { $regex: `^${prefix}` }
  }).sort({ voucherNumber: -1 });
  
  let sequence = 1;
  if (lastJournal && lastJournal.voucherNumber) {
    const parts = lastJournal.voucherNumber.split('-');
    const lastSeq = parseInt(parts[parts.length - 1]);
    if (!isNaN(lastSeq)) {
      sequence = lastSeq + 1;
    }
  }
  
  return `${prefix}-${String(sequence).padStart(4, '0')}`;
};

/**
 * Create automatic journal entry for Dealer Invoice
 * Debit: Sundry Debtors
 * Credit: Sales Account
 * Credit: GST Payable (if GST applicable)
 */
export const createDealerInvoiceEntry = async (invoice, dbConnection, userId) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    
    console.log(`📝 Creating automatic journal entry for Dealer Invoice: ${invoice.invoiceNumber}`);
    
    // Get system accounts
    const debtorsAccount = await getSystemAccount('Sundry Debtors', dbConnection);
    const salesAccount = await getSystemAccount('Sales Account', dbConnection);
    const gstPayableAccount = await getSystemAccount('GST Payable', dbConnection);
    
    if (!debtorsAccount || !salesAccount) {
      console.error('❌ Required system accounts not found');
      return null;
    }
    
    const entries = [];
    
    // Handle both gstAmount and totalGst field names
    const gstAmount = invoice.gstAmount || invoice.totalGst || 0;
    
    // Debit: Sundry Debtors (Total Amount including GST)
    entries.push({
      accountId: debtorsAccount._id,
      accountName: debtorsAccount.accountName,
      accountGroup: debtorsAccount.accountGroup,
      debit: invoice.totalAmount,
      credit: 0,
      narration: `Sales to ${invoice.dealerName || 'Dealer'} - Invoice ${invoice.invoiceNumber}`
    });
    
    // Credit: Sales Account (Subtotal without GST)
    entries.push({
      accountId: salesAccount._id,
      accountName: salesAccount.accountName,
      accountGroup: salesAccount.accountGroup,
      debit: 0,
      credit: invoice.subtotal,
      narration: `Sales - Invoice ${invoice.invoiceNumber}`
    });
    
    // Credit: GST Payable (GST Amount)
    if (gstAmount && gstAmount > 0 && gstPayableAccount) {
      entries.push({
        accountId: gstPayableAccount._id,
        accountName: gstPayableAccount.accountName,
        accountGroup: gstPayableAccount.accountGroup,
        debit: 0,
        credit: gstAmount,
        narration: `GST on Sales - Invoice ${invoice.invoiceNumber}`
      });
    }
    
    const voucherNumber = await generateJournalNumber(dbConnection);
    
    const journalVoucher = await JournalVoucher.create({
      voucherNumber,
      voucherDate: invoice.invoiceDate || new Date(),
      voucherType: 'Sales',
      referenceType: 'DealerInvoice',
      referenceId: invoice._id,
      referenceNumber: invoice.invoiceNumber,
      entries,
      totalDebit: invoice.totalAmount,
      totalCredit: invoice.totalAmount,
      narration: `Automatic entry for Dealer Invoice ${invoice.invoiceNumber}`,
      isAutoGenerated: true,
      createdBy: userId
    });
    
    console.log(`✅ Journal entry created: ${voucherNumber}`);
    return journalVoucher;
    
  } catch (error) {
    console.error('❌ Error creating dealer invoice journal entry:', error);
    return null;
  }
};

/**
 * Create automatic journal entry for Supplier Invoice
 * Debit: Purchase Account
 * Debit: GST Input Credit (if GST applicable)
 * Credit: Sundry Creditors
 */
export const createSupplierInvoiceEntry = async (invoice, dbConnection, userId) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    
    console.log(`📝 Creating automatic journal entry for Supplier Invoice: ${invoice.invoiceNumber}`);
    
    // Get system accounts
    const creditorsAccount = await getSystemAccount('Sundry Creditors', dbConnection);
    const purchaseAccount = await getSystemAccount('Purchase Account', dbConnection);
    const gstInputAccount = await getSystemAccount('GST Input Credit', dbConnection);
    
    if (!creditorsAccount || !purchaseAccount) {
      console.error('❌ Required system accounts not found');
      return null;
    }
    
    const entries = [];
    
    // Handle both gstAmount and totalGst field names (embedded GST, reverse-calculated)
    const gstAmount = invoice.gstAmount || invoice.totalGst || 0;

    // totalAmount is GST-INCLUSIVE (MRP-based). Split it for double-entry:
    //   Purchase Account (base, GST-exclusive) + GST Input Credit (embedded GST) = Creditors (inclusive)
    const purchaseBase = (invoice.totalAmount || 0) - gstAmount;

    // Debit: Purchase Account (base value, excluding embedded GST)
    entries.push({
      accountId: purchaseAccount._id,
      accountName: purchaseAccount.accountName,
      accountGroup: purchaseAccount.accountGroup,
      debit: purchaseBase,
      credit: 0,
      narration: `Purchase from ${invoice.supplierName || 'Supplier'} - Invoice ${invoice.invoiceNumber}`
    });
    
    // Debit: GST Input Credit (GST Amount)
    if (gstAmount && gstAmount > 0 && gstInputAccount) {
      entries.push({
        accountId: gstInputAccount._id,
        accountName: gstInputAccount.accountName,
        accountGroup: gstInputAccount.accountGroup,
        debit: gstAmount,
        credit: 0,
        narration: `GST on Purchase - Invoice ${invoice.invoiceNumber}`
      });
    }
    
    // Credit: Sundry Creditors (Total Amount including GST)
    entries.push({
      accountId: creditorsAccount._id,
      accountName: creditorsAccount.accountName,
      accountGroup: creditorsAccount.accountGroup,
      debit: 0,
      credit: invoice.totalAmount,
      narration: `Purchase from ${invoice.supplierName || 'Supplier'} - Invoice ${invoice.invoiceNumber}`
    });
    
    const voucherNumber = await generateJournalNumber(dbConnection);
    
    const journalVoucher = await JournalVoucher.create({
      voucherNumber,
      voucherDate: invoice.invoiceDate || new Date(),
      voucherType: 'Purchase',
      referenceType: 'SupplierInvoice',
      referenceId: invoice._id,
      referenceNumber: invoice.invoiceNumber,
      entries,
      totalDebit: invoice.totalAmount,
      totalCredit: invoice.totalAmount,
      narration: `Automatic entry for Supplier Invoice ${invoice.invoiceNumber}`,
      isAutoGenerated: true,
      createdBy: userId
    });
    
    console.log(`✅ Journal entry created: ${voucherNumber}`);
    return journalVoucher;
    
  } catch (error) {
    console.error('❌ Error creating supplier invoice journal entry:', error);
    return null;
  }
};

/**
 * Create automatic journal entry for Dealer Payment (Receipt)
 * Debit: Bank/Cash Account
 * Credit: Sundry Debtors
 */
export const createDealerPaymentEntry = async (payment, dbConnection, userId) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    
    console.log(`📝 Creating automatic journal entry for Dealer Payment: ${payment.paymentNumber}`);
    
    // Get system accounts
    const debtorsAccount = await getSystemAccount('Sundry Debtors', dbConnection);
    const cashAccount = await getSystemAccount('Cash Account', dbConnection);
    const bankAccount = await getSystemAccount('Bank Account', dbConnection);
    
    if (!debtorsAccount || (!cashAccount && !bankAccount)) {
      console.error('❌ Required system accounts not found');
      return null;
    }
    
    // Determine which account to use based on payment mode
    const paymentAccount = payment.paymentMode === 'Cash' ? cashAccount : bankAccount;
    
    const entries = [
      {
        accountId: paymentAccount._id,
        accountName: paymentAccount.accountName,
        accountGroup: paymentAccount.accountGroup,
        debit: payment.amount,
        credit: 0,
        narration: `Payment received from ${payment.dealerName || 'Dealer'} - ${payment.paymentNumber}`
      },
      {
        accountId: debtorsAccount._id,
        accountName: debtorsAccount.accountName,
        accountGroup: debtorsAccount.accountGroup,
        debit: 0,
        credit: payment.amount,
        narration: `Payment from ${payment.dealerName || 'Dealer'} - ${payment.paymentNumber}`
      }
    ];
    
    const voucherNumber = await generateJournalNumber(dbConnection);
    
    const journalVoucher = await JournalVoucher.create({
      voucherNumber,
      voucherDate: payment.paymentDate || new Date(),
      voucherType: 'Receipt',
      referenceType: 'DealerPayment',
      referenceId: payment._id,
      referenceNumber: payment.paymentNumber,
      entries,
      totalDebit: payment.amount,
      totalCredit: payment.amount,
      narration: `Automatic entry for Dealer Payment ${payment.paymentNumber}`,
      isAutoGenerated: true,
      createdBy: userId
    });
    
    console.log(`✅ Journal entry created: ${voucherNumber}`);
    return journalVoucher;
    
  } catch (error) {
    console.error('❌ Error creating dealer payment journal entry:', error);
    return null;
  }
};

/**
 * Create automatic journal entry for Supplier Payment
 * Debit: Sundry Creditors
 * Credit: Bank/Cash Account
 */
export const createSupplierPaymentEntry = async (payment, dbConnection, userId) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    
    console.log(`📝 Creating automatic journal entry for Supplier Payment: ${payment.paymentNumber}`);
    
    // Get system accounts
    const creditorsAccount = await getSystemAccount('Sundry Creditors', dbConnection);
    const cashAccount = await getSystemAccount('Cash Account', dbConnection);
    const bankAccount = await getSystemAccount('Bank Account', dbConnection);
    
    if (!creditorsAccount || (!cashAccount && !bankAccount)) {
      console.error('❌ Required system accounts not found');
      return null;
    }
    
    // Determine which account to use based on payment mode
    const paymentAccount = payment.paymentMode === 'Cash' ? cashAccount : bankAccount;
    
    const entries = [
      {
        accountId: creditorsAccount._id,
        accountName: creditorsAccount.accountName,
        accountGroup: creditorsAccount.accountGroup,
        debit: payment.amount,
        credit: 0,
        narration: `Payment to ${payment.supplierName || 'Supplier'} - ${payment.paymentNumber}`
      },
      {
        accountId: paymentAccount._id,
        accountName: paymentAccount.accountName,
        accountGroup: paymentAccount.accountGroup,
        debit: 0,
        credit: payment.amount,
        narration: `Payment to ${payment.supplierName || 'Supplier'} - ${payment.paymentNumber}`
      }
    ];
    
    const voucherNumber = await generateJournalNumber(dbConnection);
    
    const journalVoucher = await JournalVoucher.create({
      voucherNumber,
      voucherDate: payment.paymentDate || new Date(),
      voucherType: 'Payment',
      referenceType: 'SupplierPayment',
      referenceId: payment._id,
      referenceNumber: payment.paymentNumber,
      entries,
      totalDebit: payment.amount,
      totalCredit: payment.amount,
      narration: `Automatic entry for Supplier Payment ${payment.paymentNumber}`,
      isAutoGenerated: true,
      createdBy: userId
    });
    
    console.log(`✅ Journal entry created: ${voucherNumber}`);
    return journalVoucher;
    
  } catch (error) {
    console.error('❌ Error creating supplier payment journal entry:', error);
    return null;
  }
};

/**
 * Get an expense account to debit, or create a generic one if none exists.
 * Returns an account in the 'Indirect Expenses' group.
 */
const getOrCreateExpenseAccount = async (dbConnection, preferredName) => {
  const { AccountMaster } = getModels(dbConnection);
  // 1) Exact match on the expense type name (if an account is named for it)
  if (preferredName) {
    const named = await AccountMaster.findOne({ accountName: preferredName });
    if (named) return named;
  }
  // 2) Any existing Indirect Expenses account
  const anyExpense = await AccountMaster.findOne({ accountGroup: 'Indirect Expenses' });
  if (anyExpense) return anyExpense;
  // 3) Create a fallback 'General Expenses' account
  return AccountMaster.create({
    accountName: 'General Expenses',
    accountGroup: 'Indirect Expenses',
    accountType: 'Expense',
    openingBalance: 0,
    openingBalanceType: 'Dr',
    isSystem: true,
    description: 'Auto-created for expense postings',
  });
};

/**
 * Create automatic journal entry for an Expense.
 * Debit:  Expense account (Indirect Expenses)
 * Credit: Cash Account (expenses are assumed paid in cash by default)
 */
export const createExpenseEntry = async (expense, dbConnection, userId, options = {}) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);

    const amount = Number(expense.amount) || 0;
    if (amount <= 0) return null;

    const cashAccount = await getSystemAccount('Cash Account', dbConnection);
    const expenseAccount = await getOrCreateExpenseAccount(dbConnection, options.expenseTypeName);

    if (!cashAccount || !expenseAccount) {
      console.error('❌ Required accounts not found for expense journal entry');
      return null;
    }

    const entries = [
      {
        accountId: expenseAccount._id,
        accountName: expenseAccount.accountName,
        accountGroup: expenseAccount.accountGroup,
        debit: amount,
        credit: 0,
        narration: `Expense: ${expense.description || options.expenseTypeName || 'General'}`,
      },
      {
        accountId: cashAccount._id,
        accountName: cashAccount.accountName,
        accountGroup: cashAccount.accountGroup,
        debit: 0,
        credit: amount,
        narration: `Paid for expense: ${expense.description || ''}`,
      },
    ];

    const voucherNumber = await generateJournalNumber(dbConnection);

    const journalVoucher = await JournalVoucher.create({
      voucherNumber,
      voucherDate: expense.date || new Date(),
      voucherType: 'Payment',
      referenceType: 'Manual',
      referenceId: expense._id,
      referenceNumber: String(expense._id),
      entries,
      totalDebit: amount,
      totalCredit: amount,
      totalAmount: amount,
      narration: `Automatic entry for expense ${expense.description || ''}`.trim(),
      isAutoGenerated: true,
      createdBy: userId,
    });

    return journalVoucher;
  } catch (error) {
    console.error('❌ Error creating expense journal entry:', error);
    return null;
  }
};

/**
 * Create the balancing journal entry for a dealer's opening balance (go-live).
 * Dr type (dealer owes us / receivable): Dr Sundry Debtors / Cr Opening Balance Equity.
 * Cr type (we owe dealer / advance):     Dr Opening Balance Equity / Cr Sundry Debtors.
 */
export const createDealerOpeningEntry = async ({ dealer, amount, type, date }, dbConnection, userId) => {
  try {
    const { JournalVoucher, AccountMaster } = getModels(dbConnection);
    const amt = Number(amount) || 0;
    if (amt <= 0) return null;

    const debtors = await getSystemAccount('Sundry Debtors', dbConnection);
    // Auto-create the Opening Balance Equity account if missing
    let openingEquity = await AccountMaster.findOne({ accountName: 'Opening Balance Equity' });
    if (!openingEquity) {
      openingEquity = await AccountMaster.create({
        accountName: 'Opening Balance Equity',
        accountGroup: 'Reserves & Surplus',
        accountType: 'Equity',
        openingBalance: 0,
        openingBalanceType: 'Cr',
        isSystem: true,
        description: 'Contra account for migration opening balances',
      });
    }
    if (!debtors || !openingEquity) return null;

    const dealerName = dealer?.name || 'Dealer';
    const isDr = type === 'Dr';
    const entries = isDr
      ? [
          { accountId: debtors._id, accountName: debtors.accountName, accountGroup: debtors.accountGroup, debit: amt, credit: 0, narration: `Opening balance receivable from ${dealerName}` },
          { accountId: openingEquity._id, accountName: openingEquity.accountName, accountGroup: openingEquity.accountGroup, debit: 0, credit: amt, narration: `Opening balance - ${dealerName}` },
        ]
      : [
          { accountId: openingEquity._id, accountName: openingEquity.accountName, accountGroup: openingEquity.accountGroup, debit: amt, credit: 0, narration: `Opening balance - ${dealerName}` },
          { accountId: debtors._id, accountName: debtors.accountName, accountGroup: debtors.accountGroup, debit: 0, credit: amt, narration: `Opening advance/credit for ${dealerName}` },
        ];

    const voucherNumber = await generateJournalNumber(dbConnection);
    return JournalVoucher.create({
      voucherNumber,
      voucherDate: date || new Date(),
      voucherType: 'Opening Entry',
      referenceType: 'Manual',
      referenceId: dealer?._id,
      referenceNumber: dealer?.code || '',
      entries,
      totalDebit: amt,
      totalCredit: amt,
      totalAmount: amt,
      narration: `Opening balance for dealer ${dealerName} (${type})`,
      isAutoGenerated: true,
      createdBy: userId,
    });
  } catch (error) {
    console.error('❌ Error creating dealer opening journal entry:', error);
    return null;
  }
};

/**
 * Get or create the Suspense holding account (counter for unclassified
 * cash/bank vouchers — the user reclassifies it later via a journal).
 */
const getOrCreateSuspenseAccount = async (dbConnection) => {
  const { AccountMaster } = getModels(dbConnection);
  let acc = await AccountMaster.findOne({ accountName: 'Suspense Account' });
  if (!acc) {
    acc = await AccountMaster.create({
      accountName: 'Suspense Account',
      accountGroup: 'Current Assets',
      accountType: 'Asset',
      openingBalance: 0,
      openingBalanceType: 'Dr',
      isSystem: true,
      description: 'Holding account for unclassified cash/bank vouchers — reclassify via journal',
    });
  }
  return acc;
};

const lineFor = (account, debit, credit, narration) => ({
  accountId: account._id,
  accountName: account.accountName,
  accountGroup: account.accountGroup,
  debit,
  credit,
  narration,
});

/**
 * Create automatic journal entry for a STANDALONE cash/bank voucher
 * (Receipt / Payment / Contra created via the Voucher module).
 *
 * Rules to avoid double-counting with the payment modules:
 *   - Contra (cash <-> bank): Dr destination ledger / Cr source ledger.
 *   - Receipt/Payment for Dealer or Supplier: SKIPPED — those are journalized
 *     by the Dealer/Supplier payment modules.
 *   - Other / Internal / Family-Friends Receipt: Dr Cash/Bank / Cr Suspense.
 *   - Other / Internal / Family-Friends Payment: Dr Suspense / Cr Cash/Bank.
 *
 * Idempotent: if a journal voucher already references this voucher, returns it.
 */
export const createVoucherEntry = async (voucher, dbConnection, userId) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    const amount = Number(voucher.totalAmount) || 0;
    if (amount <= 0) return null;
    if (voucher.status && voucher.status !== 'Posted') return null;

    // Idempotency — never post twice for the same voucher
    const existing = await JournalVoucher.findOne({
      referenceId: voucher._id,
      referenceNumber: voucher.voucherNumber,
    });
    if (existing) return existing;

    let entries = null;
    let jvType = 'Journal';

    if (voucher.voucherType === 'Contra') {
      const fromType = voucher.contraDetails?.fromAccount?.accountType;
      const toType = voucher.contraDetails?.toAccount?.accountType;
      if (!fromType || !toType) return null;
      const fromLedger = await getSystemAccount(fromType === 'Cash' ? 'Cash Account' : 'Bank Account', dbConnection);
      const toLedger = await getSystemAccount(toType === 'Cash' ? 'Cash Account' : 'Bank Account', dbConnection);
      if (!fromLedger || !toLedger) return null;
      jvType = 'Contra';
      const note = `Transfer ${voucher.contraDetails?.fromAccount?.accountName || fromType} → ${voucher.contraDetails?.toAccount?.accountName || toType}`;
      entries = [
        lineFor(toLedger, amount, 0, note),
        lineFor(fromLedger, 0, amount, note),
      ];
    } else if (voucher.voucherType === 'Receipt' || voucher.voucherType === 'Payment') {
      // Dealer/Supplier receipts & payments are journalized by their own modules
      if (['Dealer', 'Supplier'].includes(voucher.partyType)) return null;

      const cashBank = await getSystemAccount(voucher.transactionMode === 'Cash' ? 'Cash Account' : 'Bank Account', dbConnection);
      const suspense = await getOrCreateSuspenseAccount(dbConnection);
      if (!cashBank || !suspense) return null;

      jvType = voucher.voucherType;
      const who = voucher.partyName || voucher.partyType || 'party';
      if (voucher.voucherType === 'Receipt') {
        entries = [
          lineFor(cashBank, amount, 0, `Receipt from ${who} - ${voucher.voucherNumber}`),
          lineFor(suspense, 0, amount, `Unclassified receipt - ${voucher.voucherNumber} (reclassify)`),
        ];
      } else {
        entries = [
          lineFor(suspense, amount, 0, `Unclassified payment - ${voucher.voucherNumber} (reclassify)`),
          lineFor(cashBank, 0, amount, `Payment to ${who} - ${voucher.voucherNumber}`),
        ];
      }
    } else {
      return null; // Journal-type vouchers are handled elsewhere
    }

    const voucherNumber = await generateJournalNumber(dbConnection);
    const jv = await JournalVoucher.create({
      voucherNumber,
      voucherDate: voucher.voucherDate || new Date(),
      voucherType: jvType,
      referenceType: 'Manual',
      referenceId: voucher._id,
      referenceNumber: voucher.voucherNumber,
      entries,
      totalDebit: amount,
      totalCredit: amount,
      totalAmount: amount,
      narration: voucher.narration || `Automatic entry for ${voucher.voucherType} voucher ${voucher.voucherNumber}`,
      isAutoGenerated: true,
      createdBy: userId,
    });
    return jv;
  } catch (error) {
    console.error('❌ Error creating voucher journal entry:', error);
    return null;
  }
};

/**
 * Cancel the journal entry linked to a cash/bank voucher (on voucher cancel).
 */
export const cancelVoucherEntry = async (voucherId, dbConnection, userId, reason) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    const jv = await JournalVoucher.findOne({ referenceId: voucherId, status: 'Posted', isAutoGenerated: true });
    if (!jv) return null;
    jv.status = 'Cancelled';
    jv.cancelledAt = new Date();
    jv.cancelledBy = userId;
    jv.cancelReason = reason || 'Voucher cancelled';
    await jv.save();
    return jv;
  } catch (error) {
    console.error('❌ Error cancelling voucher journal entry:', error);
    return null;
  }
};

export default {
  createDealerInvoiceEntry,
  createSupplierInvoiceEntry,
  createDealerPaymentEntry,
  createSupplierPaymentEntry,
  createExpenseEntry,
  createDealerOpeningEntry,
  createVoucherEntry,
  cancelVoucherEntry,
};