// services/accountingService.js
// Automatic Accounting Entry Service
// Creates journal entries automatically for business transactions

import { journalVoucherSchema } from '../models/JournalVoucher.js';
import { accountMasterSchema } from '../models/AccountMaster.js';

const getModels = (dbConnection) => {
  return {
    JournalVoucher: dbConnection.models.JournalVoucher || dbConnection.model('JournalVoucher', journalVoucherSchema),
    AccountMaster: dbConnection.models.AccountMaster || dbConnection.model('AccountMaster', accountMasterSchema)
  };
};

/**
 * Get or create system account by name
 */
const getSystemAccount = async (accountName, dbConnection) => {
  const { AccountMaster } = getModels(dbConnection);
  // Try to find by name and system flag first
  let account = await AccountMaster.findOne({ accountName, isSystem: true });
  
  // If not found with system flag, try without it (for older accounts)
  if (!account) {
    account = await AccountMaster.findOne({ accountName });
  }
  
  if (!account) {
    console.warn(`⚠️ System account "${accountName}" not found. Please ensure default accounts are seeded.`);
  }
  
  return account;
};

/**
 * Generate journal voucher number
 */
const generateJournalNumber = async (dbConnection) => {
  const { JournalVoucher } = getModels(dbConnection);
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  
  const prefix = `JV-${year}${month}`;
  const lastJournal = await JournalVoucher.findOne({
    voucherNumber: { $regex: `^${prefix}` }
  }).sort({ voucherNumber: -1 });
  
  let sequence = 1;
  if (lastJournal && lastJournal.voucherNumber) {
    const parts = lastJournal.voucherNumber.split('-');
    const lastSeq = parseInt(parts[parts.length - 1]);
    if (!isNaN(lastSeq)) {
      sequence = lastSeq + 1;
    }
  }
  
  return `${prefix}-${String(sequence).padStart(4, '0')}`;
};

/**
 * Create automatic journal entry for Dealer Invoice
 * Debit: Sundry Debtors
 * Credit: Sales Account
 * Credit: GST Payable (if GST applicable)
 */
export const createDealerInvoiceEntry = async (invoice, dbConnection, userId) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    
    console.log(`📝 Creating automatic journal entry for Dealer Invoice: ${invoice.invoiceNumber}`);
    
    // Get system accounts
    const debtorsAccount = await getSystemAccount('Sundry Debtors', dbConnection);
    const salesAccount = await getSystemAccount('Sales Account', dbConnection);
    const gstPayableAccount = await getSystemAccount('GST Payable', dbConnection);
    
    if (!debtorsAccount || !salesAccount) {
      console.error('❌ Required system accounts not found');
      return null;
    }
    
    const entries = [];
    
    // Handle both gstAmount and totalGst field names
    const gstAmount = invoice.gstAmount || invoice.totalGst || 0;
    
    // Debit: Sundry Debtors (Total Amount including GST)
    entries.push({
      accountId: debtorsAccount._id,
      accountName: debtorsAccount.accountName,
      accountGroup: debtorsAccount.accountGroup,
      debit: invoice.totalAmount,
      credit: 0,
      narration: `Sales to ${invoice.dealerName || 'Dealer'} - Invoice ${invoice.invoiceNumber}`
    });
    
    // Credit: Sales Account (Subtotal without GST)
    entries.push({
      accountId: salesAccount._id,
      accountName: salesAccount.accountName,
      accountGroup: salesAccount.accountGroup,
      debit: 0,
      credit: invoice.subtotal,
      narration: `Sales - Invoice ${invoice.invoiceNumber}`
    });
    
    // Credit: GST Payable (GST Amount)
    if (gstAmount && gstAmount > 0 && gstPayableAccount) {
      entries.push({
        accountId: gstPayableAccount._id,
        accountName: gstPayableAccount.accountName,
        accountGroup: gstPayableAccount.accountGroup,
        debit: 0,
        credit: gstAmount,
        narration: `GST on Sales - Invoice ${invoice.invoiceNumber}`
      });
    }
    
    const voucherNumber = await generateJournalNumber(dbConnection);
    
    const journalVoucher = await JournalVoucher.create({
      voucherNumber,
      voucherDate: invoice.invoiceDate || new Date(),
      voucherType: 'Sales',
      referenceType: 'DealerInvoice',
      referenceId: invoice._id,
      referenceNumber: invoice.invoiceNumber,
      entries,
      totalDebit: invoice.totalAmount,
      totalCredit: invoice.totalAmount,
      narration: `Automatic entry for Dealer Invoice ${invoice.invoiceNumber}`,
      isAutoGenerated: true,
      createdBy: userId
    });
    
    console.log(`✅ Journal entry created: ${voucherNumber}`);
    return journalVoucher;
    
  } catch (error) {
    console.error('❌ Error creating dealer invoice journal entry:', error);
    return null;
  }
};

/**
 * Create automatic journal entry for Supplier Invoice
 * Debit: Purchase Account
 * Debit: GST Input Credit (if GST applicable)
 * Credit: Sundry Creditors
 */
export const createSupplierInvoiceEntry = async (invoice, dbConnection, userId) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    
    console.log(`📝 Creating automatic journal entry for Supplier Invoice: ${invoice.invoiceNumber}`);
    
    // Get system accounts
    const creditorsAccount = await getSystemAccount('Sundry Creditors', dbConnection);
    const purchaseAccount = await getSystemAccount('Purchase Account', dbConnection);
    const gstInputAccount = await getSystemAccount('GST Input Credit', dbConnection);
    
    if (!creditorsAccount || !purchaseAccount) {
      console.error('❌ Required system accounts not found');
      return null;
    }
    
    const entries = [];
    
    // Handle both gstAmount and totalGst field names (embedded GST, reverse-calculated)
    const gstAmount = invoice.gstAmount || invoice.totalGst || 0;

    // totalAmount is GST-INCLUSIVE (MRP-based). Split it for double-entry:
    //   Purchase Account (base, GST-exclusive) + GST Input Credit (embedded GST) = Creditors (inclusive)
    const purchaseBase = (invoice.totalAmount || 0) - gstAmount;

    // Debit: Purchase Account (base value, excluding embedded GST)
    entries.push({
      accountId: purchaseAccount._id,
      accountName: purchaseAccount.accountName,
      accountGroup: purchaseAccount.accountGroup,
      debit: purchaseBase,
      credit: 0,
      narration: `Purchase from ${invoice.supplierName || 'Supplier'} - Invoice ${invoice.invoiceNumber}`
    });
    
    // Debit: GST Input Credit (GST Amount)
    if (gstAmount && gstAmount > 0 && gstInputAccount) {
      entries.push({
        accountId: gstInputAccount._id,
        accountName: gstInputAccount.accountName,
        accountGroup: gstInputAccount.accountGroup,
        debit: gstAmount,
        credit: 0,
        narration: `GST on Purchase - Invoice ${invoice.invoiceNumber}`
      });
    }
    
    // Credit: Sundry Creditors (Total Amount including GST)
    entries.push({
      accountId: creditorsAccount._id,
      accountName: creditorsAccount.accountName,
      accountGroup: creditorsAccount.accountGroup,
      debit: 0,
      credit: invoice.totalAmount,
      narration: `Purchase from ${invoice.supplierName || 'Supplier'} - Invoice ${invoice.invoiceNumber}`
    });
    
    const voucherNumber = await generateJournalNumber(dbConnection);
    
    const journalVoucher = await JournalVoucher.create({
      voucherNumber,
      voucherDate: invoice.invoiceDate || new Date(),
      voucherType: 'Purchase',
      referenceType: 'SupplierInvoice',
      referenceId: invoice._id,
      referenceNumber: invoice.invoiceNumber,
      entries,
      totalDebit: invoice.totalAmount,
      totalCredit: invoice.totalAmount,
      narration: `Automatic entry for Supplier Invoice ${invoice.invoiceNumber}`,
      isAutoGenerated: true,
      createdBy: userId
    });
    
    console.log(`✅ Journal entry created: ${voucherNumber}`);
    return journalVoucher;
    
  } catch (error) {
    console.error('❌ Error creating supplier invoice journal entry:', error);
    return null;
  }
};

/**
 * Create automatic journal entry for Dealer Payment (Receipt)
 * Debit: Bank/Cash Account
 * Credit: Sundry Debtors
 */
export const createDealerPaymentEntry = async (payment, dbConnection, userId) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    
    console.log(`📝 Creating automatic journal entry for Dealer Payment: ${payment.paymentNumber}`);
    
    // Get system accounts
    const debtorsAccount = await getSystemAccount('Sundry Debtors', dbConnection);
    const cashAccount = await getSystemAccount('Cash Account', dbConnection);
    const bankAccount = await getSystemAccount('Bank Account', dbConnection);
    
    if (!debtorsAccount || (!cashAccount && !bankAccount)) {
      console.error('❌ Required system accounts not found');
      return null;
    }
    
    // Determine which account to use based on payment mode
    const paymentAccount = payment.paymentMode === 'Cash' ? cashAccount : bankAccount;
    
    const entries = [
      {
        accountId: paymentAccount._id,
        accountName: paymentAccount.accountName,
        accountGroup: paymentAccount.accountGroup,
        debit: payment.amount,
        credit: 0,
        narration: `Payment received from ${payment.dealerName || 'Dealer'} - ${payment.paymentNumber}`
      },
      {
        accountId: debtorsAccount._id,
        accountName: debtorsAccount.accountName,
        accountGroup: debtorsAccount.accountGroup,
        debit: 0,
        credit: payment.amount,
        narration: `Payment from ${payment.dealerName || 'Dealer'} - ${payment.paymentNumber}`
      }
    ];
    
    const voucherNumber = await generateJournalNumber(dbConnection);
    
    const journalVoucher = await JournalVoucher.create({
      voucherNumber,
      voucherDate: payment.paymentDate || new Date(),
      voucherType: 'Receipt',
      referenceType: 'DealerPayment',
      referenceId: payment._id,
      referenceNumber: payment.paymentNumber,
      entries,
      totalDebit: payment.amount,
      totalCredit: payment.amount,
      narration: `Automatic entry for Dealer Payment ${payment.paymentNumber}`,
      isAutoGenerated: true,
      createdBy: userId
    });
    
    console.log(`✅ Journal entry created: ${voucherNumber}`);
    return journalVoucher;
    
  } catch (error) {
    console.error('❌ Error creating dealer payment journal entry:', error);
    return null;
  }
};

/**
 * Create automatic journal entry for Supplier Payment
 * Debit: Sundry Creditors
 * Credit: Bank/Cash Account
 */
export const createSupplierPaymentEntry = async (payment, dbConnection, userId) => {
  try {
    const { JournalVoucher } = getModels(dbConnection);
    
    console.log(`📝 Creating automatic journal entry for Supplier Payment: ${payment.paymentNumber}`);
    
    // Get system accounts
    const creditorsAccount = await getSystemAccount('Sundry Creditors', dbConnection);
    const cashAccount = await getSystemAccount('Cash Account', dbConnection);
    const bankAccount = await getSystemAccount('Bank Account', dbConnection);
    
    if (!creditorsAccount || (!cashAccount && !bankAccount)) {
      console.error('❌ Required system accounts not found');
      return null;
    }
    
    // Determine which account to use based on payment mode
    const paymentAccount = payment.paymentMode === 'Cash' ? cashAccount : bankAccount;
    
    const entries = [
      {
        accountId: creditorsAccount._id,
        accountName: creditorsAccount.accountName,
        accountGroup: creditorsAccount.accountGroup,
        debit: payment.amount,
        credit: 0,
        narration: `Payment to ${payment.supplierName || 'Supplier'} - ${payment.paymentNumber}`
      },
      {
        accountId: paymentAccount._id,
        accountName: paymentAccount.accountName,
        accountGroup: paymentAccount.accountGroup,
        debit: 0,
        credit: payment.amount,
        narration: `Payment to ${payment.supplierName || 'Supplier'} - ${payment.paymentNumber}`
      }
    ];
    
    const voucherNumber = await generateJournalNumber(dbConnection);
    
    const journalVoucher = await JournalVoucher.create({
      voucherNumber,
      voucherDate: payment.paymentDate || new Date(),
      voucherType: 'Payment',
      referenceType: 'SupplierPayment',
      referenceId: payment._id,
      referenceNumber: payment.paymentNumber,
      entries,
      totalDebit: payment.amount,
      totalCredit: payment.amount,
      narration: `Automatic entry for Supplier Payment ${payment.paymentNumber}`,
      isAutoGenerated: true,
      createdBy: userId
    });
    
    console.log(`✅ Journal entry created: ${voucherNumber}`);
    return journalVoucher;
    
  } catch (error) {
    console.error('❌ Error creating supplier payment journal entry:', error);
    return null;
  }
};

export default {
  createDealerInvoiceEntry,
  createSupplierInvoiceEntry,
  createDealerPaymentEntry,
  createSupplierPaymentEntry
};
